version: '3.8'

services:
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:80"
    command: sh -c "dotnet restore && dotnet run"

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mongo-data: